# Generated by Django 4.1 on 2025-11-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revistas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revistas",
            name="issn",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="ISSN"
            ),
        ),
        migrations.AlterField(
            model_name="revistas",
            name="sub_titulo",
            field=models.CharField(max_length=300, null=True, verbose_name="Subtítulo"),
        ),
    ]
