# Generated by Django 5.2.6 on 2025-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('sub_titulo', models.CharField(max_length=300, verbose_name='Subtítulo')),
                ('colecao', models.CharField(max_length=300, verbose_name='Coleção')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição')),
                ('edicao', models.CharField(max_length=300, verbose_name='Edição')),
                ('local', models.CharField(max_length=300, verbose_name='Local')),
                ('editora', models.CharField(max_length=300, verbose_name='Editora')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes_ano_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('paginas', models.IntegerField(verbose_name='Páginas')),
                ('volume', models.CharField(max_length=300, verbose_name='Volume')),
                ('tomo', models.CharField(max_length=300, verbose_name='Tomo')),
                ('chamada', models.CharField(max_length=300, verbose_name='Chamada')),
                ('num_tombamento', models.CharField(max_length=300, verbose_name='Nº de Tombamento')),
                ('assunto', models.CharField(max_length=300, verbose_name='Assunto')),
                ('area_acervo', models.CharField(max_length=300, verbose_name='Área do Acervo')),
                ('referencia_ABNT', models.TextField(blank=True, null=True, verbose_name='Referência ABNT')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('disponibilidade', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
