# Generated by Django 5.2.6 on 2025-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('sub_titulo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtítulo')),
                ('issn', models.CharField(max_length=20, unique=True, verbose_name='ISSN')),
                ('frequencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Frequência')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Início de Publicação')),
                ('periodo_fim', models.DateField(blank=True, null=True, verbose_name='Fim de Publicação')),
                ('volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='Volume')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número')),
                ('editora', models.CharField(blank=True, max_length=200, null=True, verbose_name='Editora')),
                ('local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local')),
                ('assunto', models.CharField(blank=True, max_length=300, null=True, verbose_name='Assunto')),
                ('area_acervo', models.CharField(blank=True, max_length=300, null=True, verbose_name='Área do Acervo')),
                ('referencia_ABNT', models.TextField(blank=True, null=True, verbose_name='Referência ABNT')),
                ('nota', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('disponibilidade', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
