# Generated by Django 4.1 on 2025-11-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("periodicos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicos",
            name="chamada",
            field=models.CharField(max_length=300, null=True, verbose_name="Chamada"),
        ),
        migrations.AddField(
            model_name="periodicos",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="periodicos",
            name="num_tombamento",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nº de Tombamento"
            ),
        ),
        migrations.AlterField(
            model_name="periodicos",
            name="area_acervo",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Área do Acervo"
            ),
        ),
        migrations.AlterField(
            model_name="periodicos",
            name="local",
            field=models.CharField(max_length=200, null=True, verbose_name="Local"),
        ),
        migrations.AlterField(
            model_name="periodicos",
            name="sub_titulo",
            field=models.CharField(max_length=300, null=True, verbose_name="Subtítulo"),
        ),
    ]
