# Generated by Django 4.1 on 2025-10-25 00:02

import arquivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arquivos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, verbose_name="Título")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "colecao",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Coleção"
                    ),
                ),
                (
                    "tipo_arquivo",
                    models.CharField(max_length=100, verbose_name="Tipo de Arquivo"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=arquivos.models.caminho_arquivo,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Autor"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "assunto",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Assunto"
                    ),
                ),
                (
                    "area_acervo",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Área do Acervo",
                    ),
                ),
                (
                    "chamada",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Chamada"
                    ),
                ),
                (
                    "num_tombamento",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Nº de Tombamento",
                    ),
                ),
                (
                    "referencia_ABNT",
                    models.TextField(
                        blank=True, null=True, verbose_name="Referência ABNT"
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                ("disponibilidade", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Arquivo",
                "verbose_name_plural": "Arquivos",
                "ordering": ["-data_cadastro"],
            },
        ),
    ]
